# Generated by Django 5.1.1 on 2025-03-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paquete_interesados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcol_interesado',
            name='ext_PID',
        ),
        migrations.RemoveField(
            model_name='historicalcol_interesado',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcol_miembros',
            name='agrupacion',
        ),
        migrations.RemoveField(
            model_name='historicalcol_miembros',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcol_miembros',
            name='interesado',
        ),
        migrations.RemoveField(
            model_name='historicalcr_agrupacioninteresados',
            name='agrupacion_interesados',
        ),
        migrations.RemoveField(
            model_name='historicalcr_agrupacioninteresados',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallc_interesadocontacto',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallc_interesadocontacto',
            name='interesado',
        ),
        migrations.DeleteModel(
            name='HistoricalCOL_AgrupacionInteresados',
        ),
        migrations.DeleteModel(
            name='HistoricalCOL_Interesado',
        ),
        migrations.DeleteModel(
            name='Historicalcol_miembros',
        ),
        migrations.DeleteModel(
            name='HistoricalCR_AgrupacionInteresados',
        ),
        migrations.DeleteModel(
            name='HistoricalLC_InteresadoContacto',
        ),
    ]
