# Generated by Django 5.1.1 on 2025-05-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquete_interesados', '0004_historicalcol_agrupacioninteresados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='col_agrupacioninteresados',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='col_interesado',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='col_miembros',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='cr_agrupacioninteresados',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='cr_interesado',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcol_agrupacioninteresados',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcol_interesado',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcol_miembros',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcr_agrupacioninteresados',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcr_interesado',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicallc_interesadocontacto',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='lc_interesadocontacto',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
    ]
