# Generated by Django 5.1.1 on 2025-05-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquete_administrativo', '0003_historicalcol_drr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='col_drr',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='col_unidadadministrativabasica',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='cr_datosphcondominio',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='cr_predio_copropiedad',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcol_drr',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcol_unidadadministrativabasica',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcr_datosphcondominio',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcr_predio_copropiedad',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicallc_contactovisita',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicallc_datosadicionaleslevantamientocatastral',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicallc_derecho',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicallc_predio',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='lc_contactovisita',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='lc_datosadicionaleslevantamientocatastral',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='lc_derecho',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='lc_predio',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
    ]
