# Generated by Django 5.1.1 on 2025-02-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ci_forma_presentacion_codigo',
            name='codigo',
            field=models.CharField(choices=[('Imagen', 'Imagen'), ('Documento', 'Documento'), ('Mapa', 'Mapa'), ('Video', 'Video')], max_length=50, verbose_name='Tipos de formatos de presentación de la fuente'),
        ),
        migrations.AlterField(
            model_name='historicalci_forma_presentacion_codigo',
            name='codigo',
            field=models.CharField(choices=[('Imagen', 'Imagen'), ('Documento', 'Documento'), ('Mapa', 'Mapa'), ('Video', 'Video')], max_length=50, verbose_name='Tipos de formatos de presentación de la fuente'),
        ),
        migrations.AlterField(
            model_name='historicallc_fuenteadministrativatipo',
            name='tipo',
            field=models.CharField(choices=[('Documento_Privado', 'Documento privado'), ('Escritura_Publica', 'Escritura pública (Documento público)'), ('Sentencia_Judicial', 'Sentencia judicial (Documento público)'), ('Acto_Administrativo', 'Acto administrativo (Documento público)'), ('Sin_Documento', 'Sin documento')], max_length=100, verbose_name='Tipos de documentos.'),
        ),
        migrations.AlterField(
            model_name='lc_fuenteadministrativatipo',
            name='tipo',
            field=models.CharField(choices=[('Documento_Privado', 'Documento privado'), ('Escritura_Publica', 'Escritura pública (Documento público)'), ('Sentencia_Judicial', 'Sentencia judicial (Documento público)'), ('Acto_Administrativo', 'Acto administrativo (Documento público)'), ('Sin_Documento', 'Sin documento')], max_length=100, verbose_name='Tipos de documentos.'),
        ),
    ]
