# Generated by Django 5.1.1 on 2025-05-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominios', '0004_historicalci_forma_presentacion_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ci_forma_presentacion_codigo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='claseviaprincipalclase',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='col_areatipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='col_dimensiontipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='col_estadodisponibilidadtipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='col_fuenteadministrativatipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='col_fuenteespacialtipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='col_grupointeresadotipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='col_relacionsuperficietipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='col_unidadadministrativabasicatipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='col_volumentipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='cr_construccionplantatipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='cr_documentotipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='cr_grupoetnicotipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='cr_interesadotipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='cr_sexotipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='cr_unidadconstrucciontipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='cr_usouconstipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='geometriaclase',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalci_forma_presentacion_codigo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalclaseviaprincipalclase',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcol_areatipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcol_dimensiontipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcol_estadodisponibilidadtipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcol_fuenteadministrativatipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcol_fuenteespacialtipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcol_grupointeresadotipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcol_relacionsuperficietipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcol_unidadadministrativabasicatipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcol_volumentipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcr_construccionplantatipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcr_documentotipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcr_grupoetnicotipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcr_interesadotipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcr_sexotipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcr_unidadconstrucciontipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcr_usouconstipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalgeometriaclase',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicallc_condicionprediotipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicallc_derechotipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicallc_destinacioneconomicatipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicallc_fuenteadministrativatipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicallc_prediotipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicallc_resultadovisitatipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalsectortipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicaltipodirecciontipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicaltiponovedadfmitipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicaltiponovedadtipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='lc_condicionprediotipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='lc_derechotipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='lc_destinacioneconomicatipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='lc_fuenteadministrativatipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='lc_prediotipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='lc_resultadovisitatipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='sectortipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='tipodirecciontipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='tiponovedadfmitipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='tiponovedadtipo',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
    ]
