# Generated by Django 5.1.1 on 2025-03-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soporte_documental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcol_fuenteadministrativa',
            name='fuente',
        ),
        migrations.RemoveField(
            model_name='historicalcol_fuenteadministrativa',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcol_fuenteadministrativa',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='historicalcol_fuenteespacial',
            name='fuente',
        ),
        migrations.RemoveField(
            model_name='historicalcol_fuenteespacial',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcol_fuenteespacial',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='historicalcr_fuenteespacial',
            name='fuente_espacial',
        ),
        migrations.RemoveField(
            model_name='historicalcr_fuenteespacial',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcr_fuenteespacial',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='historicallc_fuenteadministrativa',
            name='fuente_administrativa',
        ),
        migrations.RemoveField(
            model_name='historicallc_fuenteadministrativa',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallc_fuenteadministrativa',
            name='tipo_documento',
        ),
        migrations.DeleteModel(
            name='HistoricalCOL_Fuente',
        ),
        migrations.DeleteModel(
            name='HistoricalCOL_FuenteAdministrativa',
        ),
        migrations.DeleteModel(
            name='HistoricalCOL_FuenteEspacial',
        ),
        migrations.DeleteModel(
            name='HistoricalCR_FuenteEspacial',
        ),
        migrations.DeleteModel(
            name='HistoricalLC_FuenteAdministrativa',
        ),
    ]
