# Generated by Django 5.1.1 on 2025-03-06 14:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominios', '0004_historicalci_forma_presentacion_codigo_and_more'),
        ('estructuras', '0004_historicalcol_areavalor_historicalcol_volumenvalor_and_more'),
        ('soporte_documental', '0002_remove_historicalcol_fuenteadministrativa_fuente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCOL_Fuente',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Elimnación')),
                ('fecha_documento_fuente', models.DateField(blank=True, help_text='Fecha de expedición del documento fuente', null=True, verbose_name='Fecha de documento fuente')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('estado_disponibilidad', models.ForeignKey(blank=True, db_constraint=False, help_text='Indica si la fuente está o no disponible y en qué condiciones', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dominios.col_estadodisponibilidadtipo', verbose_name='Estado de disponibilidad')),
                ('ext_archivo_id', models.ForeignKey(blank=True, db_constraint=False, help_text='Identificador del archivo fuente controlado por una clase externa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='estructuras.extarchivo', verbose_name='Ext archivo id')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_principal', models.ForeignKey(blank=True, db_constraint=False, help_text='Tipo de formato en el que es presentada la fuente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dominios.ci_forma_presentacion_codigo', verbose_name='Tipo principal')),
            ],
            options={
                'verbose_name': 'historical Fuente',
                'verbose_name_plural': 'historical Fuentes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCOL_FuenteAdministrativa',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Elimnación')),
                ('observacion', models.CharField(blank=True, help_text='Observaciones o descripciones del documento de la fuente administrativa', max_length=250, null=True, verbose_name='Observación')),
                ('numero_fuente', models.CharField(blank=True, help_text='Identificador del documento (número de resolución, escritura pública, radicado de una sentencia)', max_length=50, null=True, verbose_name='Número de fuente')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fuente', models.ForeignKey(blank=True, db_constraint=False, help_text='Id de la fuente.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='soporte_documental.col_fuente', verbose_name='ID Fuente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(blank=True, db_constraint=False, help_text='Tipo de documento de fuente administrativa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dominios.col_fuenteadministrativatipo', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'historical Fuente Administrativa (COL)',
                'verbose_name_plural': 'historical Fuentes Administrativas (COL)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCOL_FuenteEspacial',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Elimnación')),
                ('nombre', models.CharField(help_text='Nombre de la fuente espacial del levantamiento catastral de un predio.', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción de la fuente espacial.', max_length=250, null=True, verbose_name='Descripción')),
                ('metadato', models.CharField(blank=True, help_text='Metadato de la fuente espacial.', max_length=250, null=True, verbose_name='Metadata')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fuente', models.ForeignKey(blank=True, db_constraint=False, help_text='Id de la fuente.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='soporte_documental.col_fuente', verbose_name='ID Fuente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(blank=True, db_constraint=False, help_text='Tipo de fuente espacial.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dominios.col_fuenteespacialtipo', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'historical Fuente Espacial (COL)',
                'verbose_name_plural': 'historical Fuentes Espaciales (COL)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCR_FuenteEspacial',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Elimnación')),
                ('metadato_FE', models.CharField(blank=True, help_text='Corresponde a la ficha técnica y especificaciones del insumo utlizado para el levantamiento catastral.', max_length=250, null=True, verbose_name='Metadato')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fuente_espacial', models.ForeignKey(blank=True, db_constraint=False, help_text='Id de la fuente espacial.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='soporte_documental.col_fuenteespacial', verbose_name='ID Fuente Espacial')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(blank=True, db_constraint=False, help_text='Insumos utilizados para la obtención de infromación espacial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dominios.col_fuenteespacialtipo', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'historical Fuente Espacial (CR)',
                'verbose_name_plural': 'historical Fuentes Espaciales (CR)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLC_FuenteAdministrativa',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Elimnación')),
                ('ente_emisor', models.CharField(blank=True, help_text='Entidades encargadas de mitir el título de dominio, posesión u ocupación.', max_length=200, null=True, verbose_name='Ente emisor')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fuente_administrativa', models.ForeignKey(blank=True, db_constraint=False, help_text='Id de la fuente administrativa.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='soporte_documental.col_fuenteadministrativa', verbose_name='ID Fuente Administrativa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_documento', models.ForeignKey(blank=True, db_constraint=False, help_text='Documento que acredita la adquisición de derechos de dominio sobre un inmueble', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dominios.lc_fuenteadministrativatipo', verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'historical Fuente Administrativa (LC)',
                'verbose_name_plural': 'historical Fuentes Administrativas (LC)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
