# Generated by Django 5.1.1 on 2025-05-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte_documental', '0003_historicalcol_fuente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='col_fuente',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='col_fuenteadministrativa',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='col_fuenteespacial',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='cr_fuenteespacial',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcol_fuente',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcol_fuenteadministrativa',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcol_fuenteespacial',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicalcr_fuenteespacial',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='historicallc_fuenteadministrativa',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
        migrations.AlterField(
            model_name='lc_fuenteadministrativa',
            name='deleted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Elimnación'),
        ),
    ]
