# Generated by Django 5.1.1 on 2025-01-26 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dominios', '0001_initial'),
        ('estructuras', '0001_initial'),
        ('paquete_administrativo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='extdireccion',
            name='predio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='paquete_administrativo.lc_predio', verbose_name='predio'),
        ),
        migrations.AddField(
            model_name='extdireccion',
            name='sector_ciudad',
            field=models.ForeignKey(blank=True, help_text='Sector de la ciudad', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciudades', to='dominios.sectortipo'),
        ),
        migrations.AddField(
            model_name='extdireccion',
            name='sector_predio',
            field=models.ForeignKey(blank=True, help_text='Sector del predio', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='predios', to='dominios.sectortipo'),
        ),
        migrations.AddField(
            model_name='extdireccion',
            name='tipo_direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direcciones', to='dominios.tipodirecciontipo', verbose_name='Tipo de dirección'),
        ),
        migrations.AddField(
            model_name='extinteresado',
            name='ext_direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interesados', to='estructuras.extdireccion', verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='gm_multisurface3d',
            name='clase_geometria',
            field=models.ForeignKey(help_text='Indicación a que clase pertenece la geometría (Terreno, Construcción, Únidad de construcción', on_delete=django.db.models.deletion.PROTECT, related_name='clase_geoemetria', to='dominios.geometriaclase', verbose_name='Clase'),
        ),
        migrations.AddField(
            model_name='historicalcol_areavalor',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcol_areavalor',
            name='tipo',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Indica si el valor a registra corresonde al área geográfica o alfanumérica de la base de datos catastral.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dominios.col_areatipo', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='historicalcol_volumenvalor',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcol_volumenvalor',
            name='tipo',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Indicación de si el volumen es calculado, si figura como oficial o si se da otra circunstancia.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dominios.col_volumentipo', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='historicalextarchivo',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgm_multisurface3d',
            name='clase_geometria',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Indicación a que clase pertenece la geometría (Terreno, Construcción, Únidad de construcción', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dominios.geometriaclase', verbose_name='Clase'),
        ),
        migrations.AddField(
            model_name='historicalgm_multisurface3d',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lc_estructuranovedadnumeropredial',
            name='tipo_novedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='dominios.tiponovedadtipo', verbose_name='Tipo de novedad'),
        ),
        migrations.AddField(
            model_name='lc_novedadfmi',
            name='tipo_novedadFMI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades_fmi', to='dominios.tiponovedadfmitipo', verbose_name='Tipo de novedad'),
        ),
    ]
