# Generated by Django 5.1.1 on 2025-03-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estructuras', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcol_volumenvalor',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcol_volumenvalor',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='historicalextarchivo',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalgm_multisurface3d',
            name='clase_geometria',
        ),
        migrations.RemoveField(
            model_name='historicalgm_multisurface3d',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalCOL_AreaValor',
        ),
        migrations.DeleteModel(
            name='HistoricalCOL_VolumenValor',
        ),
        migrations.DeleteModel(
            name='HistoricalExtArchivo',
        ),
        migrations.DeleteModel(
            name='HistoricalGM_MultiSurface3D',
        ),
    ]
