# Generated by Django 5.1.1 on 2025-05-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructuras', '0004_historicalcol_areavalor_historicalcol_volumenvalor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='col_areavalor',
            options={'verbose_name': 'Valor de área', 'verbose_name_plural': 'Valores de área'},
        ),
        migrations.AlterModelOptions(
            name='historicalcol_areavalor',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Valor de área', 'verbose_name_plural': 'historical Valores de área'},
        ),
        migrations.AlterField(
            model_name='col_areavalor',
            name='id_area_valor',
            field=models.CharField(help_text='Identificador único del valor de área.', max_length=50, unique=True, verbose_name='ID de Valor de área'),
        ),
        migrations.AlterField(
            model_name='extarchivo',
            name='fecha_aceptacion',
            field=models.DateField(blank=True, help_text='Fecha en la que ha sido aceptado el documento.', null=True, verbose_name='Fecha de aceptación'),
        ),
        migrations.AlterField(
            model_name='extinteresado',
            name='firma',
            field=models.CharField(blank=True, help_text='Firma del interesado.', max_length=200, null=True, verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='extinteresado',
            name='fotografia',
            field=models.CharField(blank=True, help_text='Fotografía del interesado.', max_length=200, null=True, verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='extinteresado',
            name='huella_dactilar',
            field=models.CharField(blank=True, help_text='Imagen de la huella dactilar del interesado.', max_length=200, null=True, verbose_name='Huella Dactilar'),
        ),
        migrations.AlterField(
            model_name='historicalcol_areavalor',
            name='id_area_valor',
            field=models.CharField(db_index=True, help_text='Identificador único del valor de área.', max_length=50, verbose_name='ID de Valor de área'),
        ),
        migrations.AlterField(
            model_name='historicalextarchivo',
            name='fecha_aceptacion',
            field=models.DateField(blank=True, help_text='Fecha en la que ha sido aceptado el documento.', null=True, verbose_name='Fecha de aceptación'),
        ),
        migrations.AlterField(
            model_name='historicalextinteresado',
            name='firma',
            field=models.CharField(blank=True, help_text='Firma del interesado.', max_length=200, null=True, verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='historicalextinteresado',
            name='fotografia',
            field=models.CharField(blank=True, help_text='Fotografía del interesado.', max_length=200, null=True, verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='historicalextinteresado',
            name='huella_dactilar',
            field=models.CharField(blank=True, help_text='Imagen de la huella dactilar del interesado.', max_length=200, null=True, verbose_name='Huella Dactilar'),
        ),
    ]
