# Generated by Django 5.1.1 on 2025-01-27 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructuras', '0002_initial'),
        ('paquete_unidad_espacial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cr_construccion',
            name='geometria_construccion',
            field=models.ForeignKey(help_text='Identificador de la geometría de la construcción', limit_choices_to={'clase_geometria': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='construcciones', to='estructuras.gm_multisurface3d', verbose_name='ID Geometría'),
        ),
        migrations.AlterField(
            model_name='cr_terreno',
            name='geometria_terreno',
            field=models.ForeignKey(help_text='Identificador de la geometría del terreno.', limit_choices_to={'clase_geometria': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='terrenos', to='estructuras.gm_multisurface3d', verbose_name='ID Geometría'),
        ),
        migrations.AlterField(
            model_name='cr_unidadconstruccion',
            name='geometria_unidad_construccion',
            field=models.ForeignKey(help_text='Identificador de la geometría de la unidad de construcción', limit_choices_to={'clase_geometria': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='unidades_construcciones', to='estructuras.gm_multisurface3d', verbose_name='ID Geometría'),
        ),
        migrations.AlterField(
            model_name='historicalcr_construccion',
            name='geometria_construccion',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Identificador de la geometría de la construcción', limit_choices_to={'clase_geometria': 2}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='estructuras.gm_multisurface3d', verbose_name='ID Geometría'),
        ),
        migrations.AlterField(
            model_name='historicalcr_terreno',
            name='geometria_terreno',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Identificador de la geometría del terreno.', limit_choices_to={'clase_geometria': 1}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='estructuras.gm_multisurface3d', verbose_name='ID Geometría'),
        ),
        migrations.AlterField(
            model_name='historicalcr_unidadconstruccion',
            name='geometria_unidad_construccion',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Identificador de la geometría de la unidad de construcción', limit_choices_to={'clase_geometria': 3}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='estructuras.gm_multisurface3d', verbose_name='ID Geometría'),
        ),
    ]
