# Generated by Django 5.1.1 on 2025-03-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paquete_unidad_espacial', '0002_alter_cr_construccion_geometria_construccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcr_caracteristicasunidadconstruccion',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcr_caracteristicasunidadconstruccion',
            name='tipo_unidad_construccion',
        ),
        migrations.RemoveField(
            model_name='historicalcr_caracteristicasunidadconstruccion',
            name='uso',
        ),
        migrations.RemoveField(
            model_name='historicalcr_construccion',
            name='geometria_construccion',
        ),
        migrations.RemoveField(
            model_name='historicalcr_construccion',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcr_construccion',
            name='unidad_espacial',
        ),
        migrations.RemoveField(
            model_name='historicalcr_terreno',
            name='geometria_terreno',
        ),
        migrations.RemoveField(
            model_name='historicalcr_terreno',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcr_terreno',
            name='unidad_espacial',
        ),
        migrations.RemoveField(
            model_name='historicalcr_unidadconstruccion',
            name='caracteristicas',
        ),
        migrations.RemoveField(
            model_name='historicalcr_unidadconstruccion',
            name='construccion',
        ),
        migrations.RemoveField(
            model_name='historicalcr_unidadconstruccion',
            name='geometria_unidad_construccion',
        ),
        migrations.RemoveField(
            model_name='historicalcr_unidadconstruccion',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcr_unidadconstruccion',
            name='tipo_planta',
        ),
        migrations.RemoveField(
            model_name='historicalcr_unidadconstruccion',
            name='unidad_espacial',
        ),
        migrations.DeleteModel(
            name='HistoricalCOL_UnidadEspacial',
        ),
        migrations.DeleteModel(
            name='HistoricalCR_CaracteristicasUnidadConstruccion',
        ),
        migrations.DeleteModel(
            name='HistoricalCR_Construccion',
        ),
        migrations.DeleteModel(
            name='HistoricalCR_Terreno',
        ),
        migrations.DeleteModel(
            name='HistoricalCR_UnidadConstruccion',
        ),
    ]
